### ISSUE TITLE
Getting error: Unexpected signature algorithm 

### ISSUE THREAD

**Issue by jkancio** [OPCUAUniCT/OPCUAWebPlatformUniCT#3]
Congratulation for your pioneer job.
I'm getting the error...
Unexpected signature algorithm: ...//www.w3.org/2000/09/xmldsig#rsa-sha256
As shows attached image.
![signatureerror](https://user-images.githubusercontent.com/1507010/39958412-c80bae1a-55d8-11e8-8874-a7029d1f4904.png)

I'm using ...
 <AutoAcceptUntrustedCertificates>true</AutoAcceptUntrustedCertificates>

My other question is: **If I have to send a certificate to the server, where do I put the file?**

**Comment by msalafia** [comment]
Hi @jkancio, thank you for your compliment.

OPC UA Web Platfowm creates its own Instance Certificate once it is started. Its OPC UA layer implementation is based on OPCFoundation [reference implementation](https://github.com/OPCFoundation/UA-.NETStandard). If you look at [SampleApplication](https://github.com/OPCFoundation/UA-.NETStandard/tree/master/SampleApplications/Samples/NetCoreConsoleClient) you will see how instance certificates are managed.

Basically, you don't have to send any instance certificate to the OPC UA server because the platform create its own certificate and send it to the server during the session establishment.

Pay attention to one thing: OPC UA Server needs to **trust** the Platform instance certificate. For instance, if you are using the [**UaCppServer**](https://www.unified-automation.com/downloads/opc-ua-servers.html) by Unified Automation you have to move the platform certificate from the **rejected** folder to the **trusted** folder, as explained in [this](https://www.unified-automation.com/downloads/documentation/file/download/details/opc-ua-quickstart-guide-b0102.html) guide.

Hope this can be helpful.

**Comment by jkancio** [comment]
Thank you for your fast response.
It worked fine.
Sorry, I've not notice this detail, although it was in the documentation.
