### ISSUE TITLE
Monitor with websocket

### ISSUE THREAD

**Issue by jkancio** [OPCUAUniCT/OPCUAWebPlatformUniCT#4]
I started the Monitor using **http://{{base_url}}/api/data-sets/{{dataset-id}}/monitor**
and I used a HTML javascript code...

ws = new WebSocket(url); 
url = signalr:http://localhost:8080

and I´ve got
Uncaught DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. '**signalr**' is not allowed.

Do you have an exemple of javascript code to receive monitored data?

Thanks.

**Comment by marcostefanoscroppo** [comment]
Hi @jkancio, there is a misconception. The Monitor Service is used to publish information on a MQTT Broker or a SignalR Hub. Both are not included in the platform and must be externally implemented. The URL you provided as parameter of the Monitor Request ("signalr:http://localhost:8080") is used internally by the platform and shall be the URL of your Broker (for MQTT) or Hub (for SignalR).

So that, if you want to receive published data from the Platform, the only thing you have to do from Javascript is connect to the Broker/Hub and subscribe to the right Topic/Group.

I suggest you to start with MQTT for testing Monitor Service. For MQTT you can use Mosquitto or Mosca Broker.  For a javascript client from a browser i suggest you [this](http://www.steves-internet-guide.com/using-javascript-mqtt-client-websockets/
) guide.

In the following, if you want to try SignalR i suggest you [this](https://docs.microsoft.com/en-gb/aspnet/signalr/overview/guide-to-the-api/) official guide by Microsoft.

**Comment by jkancio** [comment]
Thanks for the clarifications. I was trying with web socket, that is not the case.
