### ISSUE TITLE
Set the "Security Mode".

### ISSUE THREAD

**Issue by jkancio** [OPCUAUniCT/OPCUAWebPlatformUniCT#5]
Is it possible to configure the client to connect to the server using the "Security Mode" of type "Sign" (no Cryptography) instead of "SignAndEncrypt" that is the mode that you are using by default? 
I mean... Where do I set the  "Security Mode" to use?

Thanks

**Comment by msalafia** [comment]
You should change the relevant code in the class **UAClient** in the method **GetSessionAsync**, because it is used the method `CoreClientUtils.SelectEndpoint(serverUrl, true, 15000);` of the OPC UA SDK which returns the endpoint with the highest level of security.

You should customize this logic if you want a different level of security.

**Comment by jkancio** [comment]
Ok, At this moment, I've changed the code to
CoreClientUtils.SelectEndpoint(serverUrl, **false,** 15000);
Later, I intend to implement more connection options.
