### ISSUE TITLE
Something wrong with authorization

### ISSUE THREAD

**Issue by NObodyGX** [OPCUAUniCT/OPCUAWebPlatformUniCT#7]
Hello, when i run the application, "An unhandled exception occurred while processing the request"

It seems like that "System.NullReferenceException:“Object reference not set to an instance of an object.” 

```
if (context.Request.Path.StartsWithSegments("/api"))
            {
                string authorization = context.Request.Headers["Authorization"];
                string token = "empty";

                if (authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                {
                    token = authorization.Substring("Bearer ".Length).Trim();
```
`authorization` is null
what should I do to solve this problem, I would appreciate it.

**Comment by msalafia** [comment]
Hi @NObodyGX, the problem is due to a missing `Authorization: Bearer {{token}}` in the HTTP Request.

If you read the [API Documentation](https://documenter.getpostman.com/view/1090837/opc-ua-web-platform/RVfyAUSR) you will find that all the `/api/*` endpoint requires authorization token which is obtained making a POST request to the `http://{{base_url}}/auth/authenticate` endpoint and passing username and password as parameter. If you are using the StubAuthenticator you can use "Admin" and "password" as username and password, respectively.

Anyway you have noticed a bug in our RefreshTokenMiddleware, so i want to thank you. I have created a branch with the bugfix named **issue-7**. You can pull this bugfix and try again: you should obtain a "401 Unauthorized" response if you don't provide a valid Authorization header.

Please refer to the pull request #8 and let me know if the issue has been solved.

**Comment by NObodyGX** [comment]
@msalafia 
I debuge that authorization get it value by
` authorization = (String.IsNullOrEmpty(authorization)) ? "Bearer " : authorization;`
and web page get HTTP ERROR 404 finally.
Should I add authorization head manually or something else? 
Thanks a lot for your help.

**Comment by msalafia** [comment]
Wait a moment, the response should return "401 UNAUTHORIZED" not 404. Try to test the platform using a tool like [Postman](https://www.getpostman.com/) according to the [API Documentation](https://documenter.getpostman.com/view/1090837/opc-ua-web-platform/RVfyAUSR). This is a pretty good way to test a Web API. Hope this could help you.
